### ISSUE TITLE
Exiting blue buggy puts you back at the point where you got in

### ISSUE THREAD

**Issue by BatedUrGonnaDie** [firestack/MarsOrBustTracker#12]
Should probably have you get out next to the buggies current location.  Might be the same with the large buggy but can't get out currently.

**Comment by firestack** [comment]
The blue buggy was intended as an RC car. there will be a better interface later to show that it is remote controlled instead of just "getting in".

**Comment by BatedUrGonnaDie** [comment]
Ah, that makes a lot more sense then.
